GET http://localhost:3000/employees

###

POST http://localhost:3000/employees
Content-Type: application/json

{
   "firstName": "Kalle",
   "lastName": "Kula",
   "jobTitle": "Manager",
   "email": "kallekula@hej.se"
 }
