GET http://localhost:3000/employees

// för att avgränsa och avsluta ett test gör man tre stycken #

//(###) 

// SKRIVA TEST MED POST 

// POST http://localhost:3000/employees
// Content-Type: application/json

# {
#   "firstName": "Therese",
#   "lastName": "Linden",
#   "jobTitle": "Manager",
#   "email": "therese@hej.se"
# }
