GET http://localhost:3000/employees

###

GET http://localhost:3000/employees/4

###


POST http://localhost:3000/employees
Content-Type: application/json

{
   "firstName": "Kalle",
   "lastName": "Kula",
   "jobTitle": "Manager",
   "email": "kallekula@hej.se"
 }

###

PUT http://localhost:3000/employees/:id
Content-Type: application/json

{
  "firstName": "Kalle",
  "lastName": "Kanonkula",
  "jobTitle": "Customer Manager",
  "email": "kallekula@hej.se"
}

###
DELETE http://localhost:3000/employees/:id